server.port=8091
server.servlet.session.cookie.name=MYAPPSESSION
spring.jpa.open-in-view=false
# ==========================================
# Database Connection Settings
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / Hibernate Settings
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ==========================================
# Thymeleaf Settings (Development Mode)
# ==========================================
spring.thymeleaf.cache=false